nombre=input("Ingrese el nombre: ")
print(nombre.upper())
print(nombre.lower())
nombres=nombre.split()
n=nombres[0]
h=len(n)
ns="".join()
letras=len(ns)
nombre=nombre.rsprit()
nombre=nombre.lsprit()
print(nombre)
print(letras)